# $Id: Makefile,v 1.1 2004/09/22 07:29:20 t-momose Exp $
# $FreeBSD: src/sys/modules/netgraph/bluetooth/Makefile,v 1.2 2003/05/10 21:44:37 julian Exp $

SUBDIR=	\
	bluetooth \
	hci	\
	l2cap	\
	socket	\
	bt3c	\
	h4	\
	ubt	\
	ubtbcmfw

.include <bsd.subdir.mk>

